/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef adConv1_H
#define adConv1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "adc_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/*Device instance number */
#define INST_ADCONV1  (1U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* User configurations */

/* Converter configuration 0 */
extern const adc_converter_config_t adConv1_ConvConfig0;

/* Channel configuration 0 */
extern adc_chan_config_t adConv1_ChnConfig0;



#endif /* adConv1_H */
