/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef enet_config_1_H
#define enet_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "enet_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
/*! @brief Device instance number */
#define INST_ENET  (0U)

/*! @brief Driver state structure which holds driver runtime data */
extern enet_state_t enetState;

/*! @brief Number of rings */
#define ENET_NUM_RINGS  (1U)

/*! @brief The MAC address of the module */
extern uint8_t enet_MacAddr[6];

/*! @brief Module configuration structure */
extern const enet_config_t enetInitConfig;

/*! @brief Buffer configuration structures */
extern const enet_buffer_config_t enet_buffConfigArr[ENET_NUM_RINGS];


#endif /* enet_config_1_H */
