/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef phy_1_H
#define phy_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "stddef.h"
#include "phy.h"
#include "phy_generic.h"
#include "phy_tja110x.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/*! @brief Number of PHY devices */
#define N_PHY_DEVS  (1U)
/*! @brief Number of PHY drivers */
#define N_PHY_DRIVERS  (1U)

/*! @brief Definition of names for the PHY instances */
#define PHY_INSTANCE_0  (0U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

extern phy_config_t  phyConfig[N_PHY_DEVS];      /*! @brief Array of PHY configuration structures */
extern phy_driver_t *phyDrivers[N_PHY_DRIVERS];  /*! @brief Array of pointers towards the driver structures */

/*! @brief PHY framework callbacks */
void link_up(uint8_t phy);
void link_down(uint8_t phy);
void sleep_request(uint8_t phy);



#endif /* phy_1_H */
