/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K148
package_id: S32K148_LQFP144
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 25abf08c-0962-47f7-ac97-4cf75328431e
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_phy_1.h"

/*******************************************************************************
 * phy_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'phy_1'
- type: 'phy'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'phy'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - phy:
    - phy_configs:
      - 0:
        - phyStdCfg:
          - name: 'PHY_INSTANCE_0'
          - type: 'PHY_TYPE_TJA110X'
          - speed: 'PHY_SPEED_1_GBPS'
          - location: 'PHY_LOCATION_EXTERNAL'
          - enetInstance: '0'
          - addr: '0'
          - clause45: 'false'
          - role: 'PHY_ROLE_AUTO'
          - linkUpEventCB: 'link_up'
          - linkDownEventCB: 'link_down'
          - autonegCompleteCB: 'NULL'
          - autonegFailedCB: 'NULL'
          - sleepRequestCB: 'sleep_request'
        - phyExtCfg_enable: 'true'
        - phyExtCfg:
          - extSubtype: 'PHY_TJA1101_2'
          - extSpecificConfig:
            - phyExtCfgTJA110x_fwdPhyLocal: 'false'
            - phyExtCfgTJA110x_fwdPhyRemote: 'false'
            - phyExtCfgTJA110x_localWakeupPhy: 'true'
            - phyExtCfgTJA110x_remoteWakeupPhy: 'false'
            - phyExtCfgTJA110x_reducedMiiDriveStrength: 'false'
          - extDeviceConfig:
            - phyExtCfgTJA110x_reducedClkDriveStrength: 'false'
            - phyExtCfgTJA110x_clkHold: 'false'
            - phyExtCfgTJA110x_wakeInRatiometricThreshold: 'true'
            - phyExtCfgTJA110x_localWuTimer: 'PHY_TJA110X_LOCALWUTIME_LONGEST'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
#define PHY_TYPE_TJA110X  (0U)

/*! @brief Array of pointers towards the driver structures */
phy_driver_t *phyDrivers[N_PHY_DRIVERS] = {&PHY_driver_tja110x};

/*! @brief Extended configuration for PHY 0 */
static phy_tja110x_config_t extendedConfig0 = {
  .fwdPhyLocal = false,
  .fwdPhyRemote = false,
  .localWakeupPhy = true,
  .remoteWakeupPhy = false,
  .reducedMiiDriveStrength = false,
  .reducedClkDriveStrength = false,
  .clkHold = false,
  .wakeInRatiometricThreshold = true,
  .localWuTimer = PHY_TJA110X_LOCALWUTIME_LONGEST
};

/*! @brief Array of PHY configuration structures */
phy_config_t  phyConfig[N_PHY_DEVS] = {
	{
	  .type = PHY_TYPE_TJA110X,
	  .speed = PHY_SPEED_1_GBPS,
	  .location = PHY_LOCATION_EXTERNAL,
	  .enetInstance = 0U,
	  .addr = 0UL,
	  .clause45 = false,
	  .role = PHY_ROLE_AUTO,
	  .linkUpEventCB = link_up,
	  .linkDownEventCB = link_down,
	  .autonegCompleteCB = NULL,
	  .autonegFailedCB = NULL,
	  .sleepRequestCB = sleep_request,
	  .extendedConfig = &extendedConfig0
	},
};


