/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K148
package_id: S32K148_LQFP144
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 9d4226f3-fb59-48a4-a595-12c836e3c8f6
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_SAI1.h"

/*******************************************************************************
 * SAI1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SAI1'
- type: 'sai_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'sai'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SAI1'
- config_sets:
  - sai_driver:
    - saiCfgArray:
      - 0:
        - saiCommonConfig:
          - name: 'SAI1_InitConfig0'
          - readOnly: 'true'
          - txOrRx: 'SAI_RX'
          - runErr: 'false'
          - syncErr: 'false'
          - frameStart: 'false'
          - transferType: 'SAI_DMA'
          - dmaChannel0: '0'
          - elementSize: '2'
          - callBack: 'NULL'
        - saiSpecificConfig:
          - mode: 'SAI_SLAVE'
          - masterClkSource: 'SAI_BUS_CLK'
          - bitClkDivisor: '0'
          - sampleRate: '16000'
          - syncMode: 'SAI_ASYNC'
          - bitClkPolar: 'false'
          - syncWidth: '16'
          - syncEarly: 'false'
          - syncPolar: 'false'
          - saiChannel0: 'true'
          - frameSize: '2'
          - maskMode: 'SAI_MASK_TRISTATE'
          - bitOrder: 'false'
          - firstWordWidth: '16'
          - otherWordsWidth: '16'
          - firstBitIndex: '0'
          - muxMode: 'SAI_MUX_DISABLED'
          - numberOfChannel: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/* User configuration */
const sai_user_config_t SAI1_InitConfig0 = {
    .BitClkDiv = 0U,
    .BitClkFreq = 512000U,
    .BitClkInternal = false,
    .ChannelEnable = SAI_CHANNEL_0,
    .BitClkNegPolar = false,
    .ElementSize = 2U,
    .FirstBitIndex = 0U,
    .FrameSize = 2U,
    .MaskMode = SAI_MASK_TRISTATE,
    .MasterClkSrc = SAI_BUS_CLK,
    .MsbFirst = false,
    .MuxMode = SAI_MUX_DISABLED,
    .ChannelCount = 2U,
    .DmaChannel[0] = 0U,
    .DmaChannel[1] = 0U,
    .DmaChannel[2] = 0U,
    .DmaChannel[3] = 0U,
    .RunErrorReport = false,
    .SyncErrorReport = false,
    .FrameStartReport = false,
    .SyncEarly = false,
    .SyncInternal = false,
    .SyncMode = SAI_ASYNC,
    .SyncNegPolar = false,
    .SyncWidth = 16,
    .TransferType = SAI_DMA,
    .Word0Width = 16U,
    .WordNWidth = 16U,
    .callback = NULL,
};
/*! Driver state structure */
sai_state_t sai1RxState0;

