/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef SAI0_H
#define SAI0_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "sai_driver.h"
#include <stddef.h>

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_SAI0  0

extern sai_state_t sai0TxState0;

extern sai_user_config_t SAI0_InitConfig0;



#endif /* SAI0_H */
