/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K148
package_id: S32K148_LQFP144
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_tcpip_stack.h"

/*******************************************************************************
 * tcpip_stack initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'tcpip_stack'
- type: 'tcpip_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'tcpip'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - tcpip_cfg:
    - generic_tab:
      - osEnable: 'true'
      - rtosChoice: 'freertos'
      - lowlevelIface: 'ENET'
      - txRingSize: '2'
      - rxRingSize: '6'
      - boolEnableHostname: 'true'
    - netifcfg_tab:
      - 0:
        - boolIface: 'true'
        - hostname: 'tcpipBoard1'
        - macAddress: '22:33:44:55:66:77'
        - boolDhcp: 'false'
        - boolAutoip: 'false'
        - ipv4Address: '192.168.0.200'
        - ipv4Subnet: '255.255.255.0'
        - ipv4Gateway: '192.168.0.1'
        - boolIpv6: 'true'
    - datalink_tab:
      - miiMode: 'RMII'
      - miiSpeed: '100M'
      - boolARP: 'true'
      - arpTableSize: '10'
      - boolARPQueue: 'true'
    - network_tab:
      - ipv4_id:
        - boolIpv4: 'true'
        - ipv4_auto_id:
          - dhcp2autoipTries: '3'
        - ipv4_extensions_id:
          - ipforward: 'false'
          - ipreassembly: 'true'
          - ipfrag: 'true'
        - ipv4_icmp:
          - icmp_enable: 'true'
          - icmp_ttl: '255'
        - ipv4_igmp:
          - igmp_enable: 'true'
    - transport_tab:
      - tcp_id:
        - boolTcp: 'true'
        - boolQueue: 'false'
        - ttl: '255'
        - mss: '1460'
        - snd_buf: '2920'
        - wnd: '60000'
        - maxrtx: '12'
        - synmaxrtx: '4'
      - udp_id:
        - boolUdp: 'true'
        - ttl: '255'
    - application_tab:
      - raw:
        - rawSettings:
          - enableRaw: 'true'
        - boolHttpdRaw: 'false'
        - boolTcpechoRaw: 'false'
        - boolUdpechoRaw: 'false'
        - boolLwiperf: 'true'
        - boolNetbios: 'false'
        - boolSntp: 'false'
        - boolNetio: 'false'
      - netconn:
        - netconnSettings:
          - netconn_semPerThread: '1'
        - boolHttpdNetconn: 'true'
        - boolTcpechoNetconn: 'true'
        - boolUdpechoNetconn: 'true'
        - boolDns: 'false'
        - boolShell: 'false'
      - socket:
        - boolChargenSocket: 'true'
        - boolSocketExamples: 'false'
        - boolRtp: 'false'
        - boolSslechoSocket: 'false'
    - memory_tab:
      - memAlign: '4'
      - memHeapSize: '20480'
      - noPacketBuf: '8'
      - noRawPcb: '4'
      - noUdpPcb: '8'
      - noTcpPcb: '8'
      - noListenTcpPcb: '8'
      - noSegmentTcpPcb: '16'
      - noActiveTimeouts: '15'
      - noStructNetbufs: '16'
      - noStructNetconns: '32'
      - noStructTcpipMsgApi: '8'
      - noStructTcpipMsgInpkt: '8'
      - noBufferInPool: '0'
    - checksum_tab:
      - boolEnableCksum: 'false'
      - checksum_id:
        - boolCksumPerNetif: 'false'
        - boolCksumIPGen: 'false'
        - boolCksumUDPGen: 'false'
        - boolCksumTCPGen: 'false'
        - boolCksumICMPGen: 'false'
        - boolCksumIPValid: 'false'
        - boolCksumUDPValid: 'false'
        - boolCksumTCPValid: 'false'
        - boolCksumICMPValid: 'false'
        - boolCksumOnCopy: 'false'
    - debug_tab:
      - enableDebug: 'false'
      - messageTypeDebug:
        - debugTrace: 'false'
        - debugState: 'false'
        - debugFresh: 'false'
        - debugHalt: 'false'
      - minDebugLevel: 'LWIP_DBG_LEVEL_ALL'
      - protocolDebug:
        - etharpDebug: 'false'
        - netifDebug: 'false'
        - pbufDebug: 'false'
        - apiLibDebug: 'false'
        - apiMsgDebug: 'false'
        - socketsDebug: 'false'
        - icmpDebug: 'false'
        - igmpDebug: 'false'
        - inetDebug: 'false'
        - ipDebug: 'false'
        - ipReassDebug: 'false'
        - rawDebug: 'false'
        - memDebug: 'false'
        - mempDebug: 'false'
        - sysDebug: 'false'
        - timersDebug: 'false'
        - tcpDebug: 'false'
        - tcpInputDebug: 'false'
        - tcpFrDebug: 'false'
        - tcpRtoDebug: 'false'
        - tcpCwndDebug: 'false'
        - tcpWndDebug: 'false'
        - tcpOutputDebug: 'false'
        - tcpRstDebug: 'false'
        - tcpQlenDebug: 'false'
        - udpDebug: 'false'
        - tcpipDebug: 'false'
        - slipDebug: 'false'
        - dhcpDebug: 'false'
        - autoipDebug: 'false'
        - dnsDebug: 'false'
        - ip6Debug: 'false'
        - pppDebug: 'false'
        - mdnsDebug: 'false'
        - mqttDebug: 'false'
        - snmpDebug: 'false'
        - sntpDebug: 'false'
        - tftpDebug: 'false'
        - pingDebug: 'false'
        - httpdDebug: 'false'
        - rtpDebug: 'false'
        - smtpDebug: 'false'
    - user_tab:
      - configUSER_SETTINGS: ''
      - boolTimevalPrivate: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* dummy_t type to bypass warning of forbids an empty translation unit */
typedef unsigned int dummy_t;

