/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef CAN_0_H
#define CAN_0_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "can_pal.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* User configuration */

extern can_user_config_t can_config0;

extern can_instance_t can_instance0;



#endif /* CAN_0_H */
