/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142W
package_id: S32K142W_LQFP64
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 9cb3b335-ff52-47b8-99d2-d514751e94e8
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_spi_pal_1.h"

/*******************************************************************************
 * spi_pal_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'spi_pal_1'
- type: 'spi_pal'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'spi_pal'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI_0'
- config_sets:
  - spi_pal:
    - spi_palMasterConfig:
      - 0:
        - name: 'LPSPI_0_MasterInitConfig0'
        - baudRate: '500000'
        - frameSize: '8'
        - bitOrder: 'SPI_TRANSFER_MSB_FIRST'
        - clockPolarity: 'SPI_ACTIVE_HIGH'
        - ssPolarity: 'SPI_ACTIVE_LOW'
        - clockPhase: 'READ_ON_ODD_EDGE'
        - whichPcs: '0'
        - transferType: 'SPI_USING_INTERRUPTS'
        - rxDMAChannel: '0'
        - txDMAChannel: '0'
        - callback: 'NULL'
        - callbackParam: 'NULL'
    - spi_palSlaveConfig:
      - 0:
        - name: 'LPSPI_0_SlaveInitConfig0'
        - frameSize: '8'
        - bitOrder: 'SPI_TRANSFER_MSB_FIRST'
        - clockPolarity: 'SPI_ACTIVE_HIGH'
        - ssPolarity: 'SPI_ACTIVE_LOW'
        - clockPhase: 'READ_ON_ODD_EDGE'
        - transferType: 'SPI_USING_INTERRUPTS'
        - rxDMAChannel: '0'
        - txDMAChannel: '0'
        - callback: 'NULL'
        - callbackParam: 'NULL'
    - quick_selection: 'spi_pal_default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
/* Define instance structure */
spi_instance_t spi_pal_1_Instance =
{
    .instType = SPI_INST_TYPE_LPSPI,
    .instIdx = 0U
};

/* SPI_PAL Master Configurations 0 */
spi_master_t LPSPI_0_MasterInitConfig0 =
{
    .baudRate         = 500000U,
    .frameSize        = 8U,
    .bitOrder         = SPI_TRANSFER_MSB_FIRST,
    .clockPolarity    = SPI_ACTIVE_HIGH,
    .ssPolarity       = SPI_ACTIVE_LOW,
    .clockPhase       = READ_ON_ODD_EDGE,
    .ssPin            = 0,
    .transferType     = SPI_USING_INTERRUPTS,
    .rxDMAChannel     = 0U,
    .txDMAChannel     = 0U,
    .callback         = NULL,
    .callbackParam    = NULL,
    .extension        = NULL
};

/* SPI_PAL Slave Configurations 0 */
spi_slave_t LPSPI_0_SlaveInitConfig0 =
{
    .frameSize        = 8U,
    .bitOrder         = SPI_TRANSFER_MSB_FIRST,
    .clockPolarity    = SPI_ACTIVE_HIGH,
    .ssPolarity       = SPI_ACTIVE_LOW,
    .clockPhase       = READ_ON_ODD_EDGE,
    .transferType     = SPI_USING_INTERRUPTS,
    .rxDMAChannel     = 0U,
    .txDMAChannel     = 0U,
    .callback         = NULL,
    .callbackParam    = NULL,
    .extension        = NULL
};



