/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K118
package_id: S32K118_LQFP64
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 12751ea2-fc78-4ff9-a2f8-da07609feabd
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_lpTmr1.h"

/*******************************************************************************
 * lpTmr1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lpTmr1'
- type: 'lptmr'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'lptmr'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPTMR_0'
- config_sets:
  - lptmr:
    - lptmrConfig:
      - 0:
        - name: 'lpTmr1_config0'
        - readOnly: 'true'
        - workMode: 'LPTMR_WORKMODE_TIMER'
        - dmaRequest: 'false'
        - interruptEnable: 'true'
        - freeRun: 'false'
        - compareValue: '10000'
        - counterUnits: 'LPTMR_COUNTER_UNITS_MICROSECONDS'
        - clockSelect: 'LPTMR_CLOCKSOURCE_PCC'
        - prescaler: 'LPTMR_PRESCALE_2'
        - bypassPrescaler: 'false'
        - pinSelect: 'LPTMR_PINSELECT_TRGMUX'
        - pinPolarity: 'LPTMR_PINPOLARITY_RISING'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/* LPTMR configuration structure 0 */
const lptmr_config_t  lpTmr1_config0 = {
  .workMode = LPTMR_WORKMODE_TIMER,
  .dmaRequest = false,
  .interruptEnable = true,
  .freeRun = false,
  .compareValue = 10000UL,
  .counterUnits = LPTMR_COUNTER_UNITS_MICROSECONDS,
  .clockSelect = LPTMR_CLOCKSOURCE_PCC,
  .prescaler = LPTMR_PRESCALE_2,
  .bypassPrescaler = false,
  .pinSelect = LPTMR_PINSELECT_TRGMUX,
  .pinPolarity = LPTMR_PINPOLARITY_RISING
};


