/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef FTFM_H
#define FTFM_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "csec_driver.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/
/*! @brief Driver state structure which holds driver runtime data */
extern csec_state_t csecState;



#endif /* FTFM_H */
