/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef quadspi_config_1_H
#define quadspi_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "quadspi_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_QUADSPI_CONFIG_1  (0U)

/* External declaration of QuadSPI state structure */
extern qspi_state_t qspiState;

/* External declaration of QuadSPI configuration structure */
extern const qspi_user_config_t qspi1_Config0;



#endif /* quadspi_config_1_H */
