/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K148
package_id: S32K148_LQFP144
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_quadspi_config_1.h"

/*******************************************************************************
 * quadspi_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'quadspi_config_1'
- type: 'quadspi_config'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'quadspi'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'QuadSPI'
- config_sets:
  - quadspi_driver:
    - qspi_state_name: 'qspiState'
    - qspiCfg:
      - name: 'qspi1_Config0'
      - readonly: 'true'
      - clock_src: 'QSPI_CLK_SRC_FIRC_DIV1'
      - divider: '2'
      - dataRate: 'QSPI_DATE_RATE_SDR'
      - dmaSupport: 'true'
      - dmaChannel: '0'
      - callback: 'NULL'
      - callbackParam: 'NULL'
      - side: 'QSPI_FLASH_SIDE_A'
      - memSize: '0x007FFFFF'
      - csHoldTime: '1'
      - csSetupTime: '1'
      - columnAddr: '0'
      - wordAddresable: 'false'
      - readMode: 'QSPI_READ_MODE_INTERNAL_SAMPLING'
      - sampleDelay: 'QSPI_SAMPLE_DELAY_1'
      - samplePhase: 'QSPI_SAMPLE_PHASE_NON_INVERTED'
      - dqsDelay: '0'
      - dqsInvert: 'false'
      - endianess: 'QSPI_END_64BIT_LE'
      - io2IdleValue: '1'
      - io3IdleValue: '1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
/* QuadSPI state structure */
qspi_state_t qspiState;

/* QuadSPI configuration structure */
const qspi_user_config_t qspi1_Config0 = {
  .clock_src = QSPI_CLK_SRC_FIRC_DIV1,
  .divider = 2U,
  .dataRate = QSPI_DATE_RATE_SDR,
  .dmaSupport = true,
  .dmaChannel = 0U,
  .callback = NULL,
  .callbackParam = NULL,
  .side = QSPI_FLASH_SIDE_A,
  .memSize = 8388607UL,
  .csHoldTime = 1U,
  .csSetupTime = 1U,
  .columnAddr = 0U,
  .wordAddresable = false,
  .readMode = QSPI_READ_MODE_INTERNAL_SAMPLING,
  .sampleDelay = QSPI_SAMPLE_DELAY_1,
  .samplePhase = QSPI_SAMPLE_PHASE_NON_INVERTED,
  .dqsDelay = 0U,
  .dqsInvert = false,
  .endianess = QSPI_END_64BIT_LE,
  .io2IdleValue = 1U,
  .io3IdleValue = 1U
};


