/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K148
package_id: S32K148_LQFP144
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_flash_mx25l6433f_1.h"

/*******************************************************************************
 * flash_mx25l6433f_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'flash_mx25l6433f_1'
- type: 'flash_mx25l6433f'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'flash_mx25l6433f'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - flash_mx25l6433f_driver:
    - flash_mx25l6433f_configurations:
      - 0:
        - configName: 'flash_mx25l6433f_Config0'
        - readOnly: 'true'
        - dmaSupport: 'true'
        - outputDriverStrength: 'FLASH_MX25L6433F_DRV_STRENGTH_HIGH'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/* User configuration 0 */
const flash_mx25l6433f_user_config_t flash_mx25l6433f_Config0 = {
    .dmaSupport           = true,
    .outputDriverStrength = FLASH_MX25L6433F_DRV_STRENGTH_HIGH
};


